spring:
  application:
    name: spurt-test
  datasource:
    url: 'jdbc:h2:mem:order_perf;MODE=MYSQL' # H2를 MySQL 모드로 설정
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
    defer-datasource-initialization: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  sql:
    init:
      mode: ALWAYS # 데이터베이스 초기화 시 data.sql을 항상 실행
  h2:
    console:
      enabled: true
      path: /h2-console
  metrics:
    tags:
      application: ${spring.application.name}
  cache:
    type: redis
  redis:
    host: localhost  # Redis 서버 주소
    port: 6379       # Redis 기본 포트
#    password: # Redis 비밀번호 (필요 시)
    lettuce:
      pool:
        max-active: 200
        max-idle: 100
        min-idle: 20
management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG