USE shop;

CREATE TABLE PRODUCT
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    SHOP_ID     BIGINT         NOT NULL,
    NAME        VARCHAR(255)   NOT NULL,
    PRICE       DECIMAL(19, 2) NOT NULL,
    DESCRIPTION TEXT           NOT NULL,
    CREATED_AT  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT_OPTION_GROUP
(
    ID         BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_ID BIGINT       NOT NULL,
    NAME       VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE PRODUCT_OPTION
(
    ID                      BIGINT PRIMARY KEY AUTO_INCREMENT,
    PRODUCT_OPTION_GROUP_ID BIGINT         NOT NULL,
    NAME                    VARCHAR(255)   NOT NULL,
    PRICE                   DECIMAL(19, 2) NOT NULL,
    CREATED_AT              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT              TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE SHOPS
(
    ID          BIGINT PRIMARY KEY AUTO_INCREMENT,
    SELLER_ID   BIGINT       NOT NULL,
    NAME        VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT         NOT NULL,
    ADDRESS     TEXT         NOT NULL,
    ZIP_CODE    VARCHAR(255) NOT NULL,
    CS_NUMBER   VARCHAR(255) NOT NULL
);

