global:
    scrape_interval:     15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'vps-api-server'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:18080']