global:
    scrape_interval:     15s
    evaluation_interval: 15s

scrape_configs:
    - job_name: 'vps-api-server'
      metrics_path: '/prefer/prometheus'
      scrape_interval: 5s
      static_configs:
          - targets: ['host.docker.internal:18080']

    - job_name: "rabbitmq-exporter"
      metrics_path: "/metrics"
      static_configs:
          - targets: ["host.docker.internal:9419"]

    - job_name: "mongodb-exporter"
      metrics_path: "/metrics"
      static_configs:
          - targets: ["host.docker.internal:9216"]
