# monitoring setting
management:
  metrics:
    tags:
      application: sample-apis
  endpoint:
    shutdown:
      enabled: false

  endpoints:
    web:
      exposure:
        include:
          - "prometheus"