server:
  port: 12290
spring:
  application:
    name: display
  data:
    mongodb:
      database: display
      username: prefer
      password: prefer
      port: 27017
      host: localhost
      authentication-database: display
      auto-index-creation: true
management:
  server:
    port: 12291
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /prefer
      exposure:
        exclude:
        include: prometheus
    jmx:
      exposure:
        exclude:
        include: prometheus