spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
