USE delivery;

CREATE TABLE DELIVERY
(
    ID              BIGINT PRIMARY KEY AUTO_INCREMENT,
    ORDER_ID        BIGINT       NOT NULL,
    RECIPIENT_NAME  VARCHAR(255) NOT NULL,
    MOBILE          VARCHAR(255) NOT NULL,
    DELIVERY_MEMO   VARCHAR(255) NOT NULL,
    ADDRESS         VARCHAR(255) NOT NULL,
    ZIP_CODE        VARCHAR(255) NOT NULL,
    DELIVERY_STATUS VARCHAR(255) NOT NULL,
    CREATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
