server:
  port: 8082
  shutdown: graceful
spring:
  application:
    name: delivery
  profiles:
    active: local
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/delivery
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    generate-ddl: false
    defer-datasource-initialization: false
management:
  server:
    port: 1${server.port}
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /prefer
      exposure:
        exclude:
        include: prometheus
    jmx:
      exposure:
        exclude:
        include: prometheus