spring:
  datasource:
    url: 'jdbc:h2:mem:order-perf-optimizer'
    username: 'user'
    password: ''
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 40              # 유지할 최소 커넥션 수
      maximum-pool-size: 400         # 최대 커넥션 수
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true
      path: '/h2-console'

server:
  port: 8082