-- product (상품 정보)
CREATE TABLE product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    brand_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    name       VARCHAR(255) NOT NULL,
    price INTEGER NOT NULL,
    description VARCHAR(255)
);

