### 샵 조회
GET http://localhost:8080/query/shops/1
Content-Type: application/json

### 샵 상품 조회
GET http://localhost:8080/query/shops/1/products
Content-Type: application/json

### 샵 상품 조회
GET http://localhost:8080/query/shops/1/products/1
Content-Type: application/json
