global:
    scrape_interval:     15s
    evaluation_interval: 15s

scrape_configs:
  - job_name: 'shop-server'
    metrics_path: '/prefer/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:18080']
  - job_name: 'order-server'
    metrics_path: '/prefer/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:18081']
  - job_name: 'delivery-server'
    metrics_path: '/prefer/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:18082']
  - job_name: 'display-server'
    metrics_path: '/prefer/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:12291']
